# web 部分
server:
  port: 1080
  servlet:
    context-path: /

spring:
  application:
    name: source-service
  datasource:
    url: jdbc:mysql://localhost:3306/source
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10

#thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl